# Generated by Django 4.2.4 on 2023-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_Prices',
            fields=[
                ('price_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(max_length=255)),
                ('fuel_price', models.FloatField()),
                ('fuel_date', models.DateField(max_length=255)),
            ],
            options={
                'db_table': 'Fuel_Prices',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('loc_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=255)),
                ('loc_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('travel_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=255)),
                ('travel_from', models.CharField(max_length=255)),
                ('travel_to', models.CharField(max_length=255)),
                ('travel_return_to', models.CharField(max_length=255)),
                ('travel_distance', models.FloatField()),
                ('cost', models.FloatField()),
                ('fuel', models.FloatField()),
            ],
            options={
                'db_table': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('emp_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_pass', models.CharField(max_length=255)),
                ('emp_addr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
