# Generated by Django 4.2.4 on 2023-08-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_Prices',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(max_length=255)),
                ('emp_id', models.CharField(max_length=255)),
                ('travel_from', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=255)),
                ('loc_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=255)),
                ('travel_from', models.CharField(max_length=255)),
                ('travel_to', models.CharField(max_length=255)),
                ('travel_return_to', models.CharField(max_length=255)),
                ('travel_distance', models.FloatField(max_length=255)),
                ('cost', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('emp_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_addr', models.CharField(max_length=255)),
            ],
        ),
    ]
