# Generated by Django 4.2.4 on 2023-08-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fuel_prices',
            table='Fuel_Prices',
        ),
        migrations.AlterModelTable(
            name='locations',
            table='Locations',
        ),
        migrations.AlterModelTable(
            name='trips',
            table='Trips',
        ),
        migrations.AlterModelTable(
            name='users',
            table='User',
        ),
    ]
