# Generated by Django 4.2.4 on 2023-08-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_fuel_prices_table_alter_locations_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='loc_id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='emp_id',
            field=models.CharField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
